# Generated by Django 4.0.10 on 2024-05-18 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=120, null=True)),
                ('last_name', models.CharField(default='', max_length=120)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
